language: node_js
node_js: stable

cache:
  directories:
    - node_modules
    
install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - cat ./index.html
  - git init
  - git config user.name "defypro"
  - git config user.email "284465256@qq.com"
  - git add .
  - git commit -m "update blog"
  - git push --force --quiet "https://${TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/defypro/defypro.github.io.git