language : node_js
node_js:
 - "10"


cache:
    apt: true
    directories:
        - node_modules

before_install:
  - npm install -g hexo
  - npm install -g hexo-cli

install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "defypro"
  - git config user.email "284465256@qq.com"
  - git add .
  - git commit -m "update blog"
  - git push --force --quiet "https://${TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/defypro/defypro.github.io